Import("env")
if env.IsIntegrationDump():
   Return()

import os
import time
import serial
from serial.tools import list_ports_windows


def doubleTap1200bpsTouch() -> bool:
    USB_COMPOSITE_ENUMERATION_DELAY = 3.0 # seconds, because windows is slow
    def touch1200bps() -> bool:
        try:
            lpwc = list_ports_windows.comports()
            if len(lpwc) == 1:
                thePort = lpwc[0].name
                s = serial.Serial(thePort, 1200)
                s.dtr = False
                time.sleep(0.4) # pulse time
                s.close()
                return True
            return False
        except:
            return False

    if touch1200bps():
        time.sleep(USB_COMPOSITE_ENUMERATION_DELAY)
        return True
    else:
        # try again after longer delay
        time.sleep(USB_COMPOSITE_ENUMERATION_DELAY)
        if touch1200bps():
            time.sleep(USB_COMPOSITE_ENUMERATION_DELAY)
            return True
        else:
            return False

def indexHTMLtoCPP() -> bool:
    os.remove("src/webserver/index.hpp")
    with open("src/webserver/index.hpp", "wt") as F_hpp:
        IndexFile = open("web/src/index.html", "rt")
        StylesFile = open("web/src/styles.css", "rt")
        ScriptFile = open("web/src/script.js", "rt")
        IndexText : str = IndexFile.read()
        StylesText : str = StylesFile.read()
        ScriptText : str = ScriptFile.read()

        print(f"\tindex.html: {len(IndexText)} bytes")
        print(f"\tstyles.css: {len(StylesText)} bytes")
        print(f"\tscript.js: {len(ScriptText)} bytes")
        bytesTotal = len(IndexText) + len(StylesText) + len(ScriptText)
        
        # todo get flash size from pio partition config
        # XIAO_ESP32S3_Plus.upload.maximum_data_size
        print(f"\tWebsite hosting uses {bytesTotal} bytes total, ({bytesTotal * 100 / 3342336 :.1f}% flash partition)") 

        IndexFile.close()
        StylesFile.close()
        ScriptFile.close()

        F_hpp.writelines([
            "/* ### DO NOT EDIT THIS FILE ### */\n",
            "/* --> This file was automatically generated by pioextra.py */\n",
            "/* --> To make changes to the web interface, see web/src/ */\n",
            "#pragma once\n",
            "namespace Web {\n",
            "const char index[] = R\"=====(\n",
            IndexText,
            ")=====\";\n",
            "const char styles[] = R\"=====(\n",
            StylesText,
            ")=====\";\n",
            "const char script[] = R\"=====(\n",
            ScriptText,
            ")=====\";\n",
            "}\n",
            ])
        
    return True


pre_success: bool = False
def pre(*_):
    print("pre()")
    global pre_success
    pre_success = True
    if not doubleTap1200bpsTouch():
        pre_success = False
    if not indexHTMLtoCPP():
        pre_success = False
    if not pre_success:
        print("EXTRA SCRIPT FAIL")

def post(source, target, env):
    print("post()")
    if not pre_success:
      return

pre()
env.AddPostAction("${BUILD_DIR}/firmware.bin", post)