; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = development

[common]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino
lib_ldf_mode = chain
lib_deps = 
	robtillaart/MCP23S17
	https://github.com/schreibfaul1/ESP32-audioI2S.git@^3.4.6
	adafruit/Adafruit GC9A01A@^1.1.0
	adafruit/SdFat - Adafruit Fork@^2.3.103
	adafruit/Adafruit ImageReader Library@^2.10.0
	ArduinoJson@^7.2.2
lib_ignore = 
	Adafruit SH110X
	Adafruit HX8357 Library
	Adafruit ILI9341,
	Adafruit seesaw Library,
	Adafruit SSD1331 OLED Driver Library for Arduino
	Adafruit SSD1351 library
	Adafruit ST7735 and ST7789 Library
	Adafruit TouchScreen
	Adafruit TSC2007
build_unflags =
	-D ARDUINO_USB_MODE=1
build_flags = 
	-D PCB_REVISION=0
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
board_build.f_cpu = 240000000


[env:development]
extends = common
board = seeed_xiao_esp32s3
build_unflags = 
	${common.build_unflags}
build_flags = 
	${common.build_flags}
	-D VERSION_DEV=1
	-D CORE_DEBUG_LEVEL=1 ; 1-5
	-D COMPILE_TIME=0
build_type = debug
upload_protocol = esptool
monitor_speed = 115200
targets = upload, monitor
extra_scripts = post:scripts/pioextra.py

[env:production]
extends = common
board = seeed_xiao_esp32_s3_plus
build_unflags = 
	${common.build_unflags}
build_flags = 
	${common.build_flags}
	-D CORE_DEBUG_LEVEL=0
	-D COMPILE_TIME=$UNIX_TIME
build_type = release
upload_protocol = esptool
targets = upload
