; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
cache_dir = .pio/cache
build_cache_dir = .pio/build_cache
default_envs = development

[common]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino
board = seeed_xiao_esp32s3 ; board = XIAO_ESP32S3_Plus ;platform_packages?
lib_ldf_mode = deep
lib_deps = 
	https://github.com/schreibfaul1/ESP32-audioI2S.git@^3.4.6
	adafruit/Adafruit GC9A01A@^1.1.0
	adafruit/SdFat - Adafruit Fork@^2.3.103
	adafruit/Adafruit ImageReader Library@^2.10.0
	ArduinoJson@^7.2.2
build_unflags =
	-DARDUINO_USB_MODE
build_flags = 
	-D PCB_REVISION=0
    -D ARDUINO_USB_MODE=1 ; 0: program by holding boot while reset. 1: USBotg/cdc mode. Serial acts weird.
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D CORE_DEBUG_LEVEL=0
board_build.board_build.f_cpu = 240000000


[env:development]
extends = common
build_unflags = 
	${common.build_unflags}
build_flags = 
	${common.build_flags}
	-D VERSION_DEV=1
	-D COMPILE_TIME=0
build_type = debug
upload_protocol = esptool
monitor_speed = 115200
targets = upload, monitor

[env:production]
extends = common
build_unflags = 
	${common.build_unflags}
build_flags = 
	${common.build_flags}
	-D COMPILE_TIME=$UNIX_TIME
build_type = release
upload_protocol = esptool
targets = upload
